name: VST.NET2 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: microsoft/setup-msbuild@v1.0.0
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest
    - name: Restore Dependencies
#      run: nuget restore Source/Code/Jacobi.Vst.sln
      run: msbuild Source/Code/Jacobi.Vst.sln /t:restore
    - name: Build VST.NET x64
      run: msbuild Source/Code/Jacobi.Vst.sln /t:Rebuild /p:Configuration=Release /p:Platform=x64
    - name: Build VST.NET x86
      run: msbuild Source/Code/Jacobi.Vst.sln /t:Rebuild /p:Configuration=Release /p:Platform=x86
